### ISSUE TITLE
Unrecognized command error in version ftb-gui-library-1605.2.1.41-forge.jar 

### ISSUE THREAD

**Issue by chocobochokeslam** [FTBTeam/FTB-Library#25]
So I am running All the mods 6, most recent version(04/24/21).  While setting up my server, I am noticing that all op related commands are triggering an error with this mod and are not functioning.  I am server owner, set by default to be made server op from the server side and I get an error when clicking change game mode, set time to day or any of the usual commands associated with being server op.  It's my own server and kind of need this working to set the server up for people.  I didn't see this listed as a known recent issue and permissions on my are set correctly so unsure what the problem is?

Thanks.

**Comment by chocobochokeslam** [comment]
for context
![image](https://user-images.githubusercontent.com/83143990/115975365-3de07480-a532-11eb-979a-14e00b2db3a9.png)

**Comment by Drakonas** [comment]
I'm having this issue as well. I am Forge 36.1.4 with ftb-gui-library 1605.2.1.41. (latest mod as of writing)

Not sure what is going on but it looks permission-related.

Be aware that I am using AMP server manager to run the forge jar.

**Comment by Drakonas** [comment]
@chocobochokeslam Found the issue. This isn't a coding problem. If you use certain packs they may not be adding ftbranks configs because it's stored in the world folder, not the configs folder.

This has to be configured in the world\serverconfig\ftbranks\ folder. Replace "world" with the name of your world.

Once I added `"command.ftbguilibrary": true` to the json file for the ranks I wanted access to be given, the command became available.

This does not require a server restart. Run the command `ftbranks reload` as an op or from the server console.
