### ISSUE TITLE
Modpack requires ftbguilibrary and won't start, despite already having it

### ISSUE THREAD

**Issue by jyetas3** [FTBTeam/FTB-Library#36]
Hello
I'm currently attempting to play a modpack i found interesting, however, if i install ftb ultimine, then ftb quests won't work because ftb library isn't installed (which it is). I am incredibly confused.
Modpack: Creative Skyblock (with additions of Halogen, Better Zoom, and FTB Ultimine)
Forge 1.16.5, Latest version
Log: https://paste.rs/LLY (idk what else to use)
How to Reproduce: Download modpack, install ftb ultimine, install ftb library and launch

![1](https://user-images.githubusercontent.com/56290667/131679641-5bf8c30d-3b1c-4044-8f19-629a225eaee3.PNG)
![2](https://user-images.githubusercontent.com/56290667/131679682-e3ddd14d-cac0-43d6-898e-06f773f70205.PNG)

If there is a seperate mod called ftb gui library, it is impossible to find

**Comment by MaxNeedsSnacks** [comment]
FTB GUI Library is now FTB Library, and this modpack seems to be severely out of date wrt FTB Quests since they're still using a version that needs GUI Library. Try either pinging the mod author to update Quests or just updating yourself, but keep in mind that your personal progress will be reset if you do
